### ISSUE TITLE
Help: Runtime Error on WSL

### ISSUE THREAD

**Issue by Rowing0914** [JamesRickards-Canada/Fundamental-domains-for-Shimura-curves#1]
Thank you for publishing your work and the codebase! I'm pretty new to GP/Pari and this is my first time to dive into actual codebase other than following the tutorial of GP/Pari websites.
Anyway, I was following your user manual and was trying to run ` ./testing/fdom-fast` but got the following error;

## Installation steps
- make setup to set Pari path
- make to compile the project and no error

## Error msg upon running `./testing/fdom-fast` on `Klein` branch
```bash
./workspace/Fundamental-domains-for-Shimura-curves$ ./testing/fdom-fast
./testing/fdom-fast: line 3: $'\r': command not found
: invalid signal specificationrap: 2
./testing/fdom-fast: line 6: $'\r': command not found
./testing/fdom-fast: line 10: $'\r': command not found
./testing/fdom-fast: line 14: $'\r': command not found
./testing/fdom-fast: line 20: $'\r': command not found
./testing/fdom-fast: line 35: syntax error near unexpected token `$'{\r''
'/testing/fdom-fast: line 35: `wrtab () {
```
Due to this error, ./testing/fdom-fast.diff has not been also generated so I have no clue how to debug... can you help me?

**Comment by JamesRickards-Canada** [comment]
Hmm, interesting!
What operating system do you run?
This method is written in shell script, and the errors you are receiving line up with where there is a blank line. There is no reason to be a blank line there other than for readability, so as a temporary fix you could try deleting all the blank lines? (if you then git pull in the future, you will have to overwrite this of course)
I will look into how to remove this. It works well on my system (Windows subsystem for Linux), as well as multiple UNIX based servers I've used, but it's possible that some systems will read this blank line as a "carriage return" and not know what to do with it. My guess is that this is what is going on.

**Comment by Rowing0914** [comment]
Hi! Thank you for your response!
Here is my system.

### Windows
![image](https://github.com/JamesRickards-Canada/Fundamental-domains-for-Shimura-curves/assets/20626792/a8bc304c-e43e-4bde-89b3-71a267d2c436)


### WSL

```NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Debug
As your advice, I removed the empty lines and the amount of error message has certainly reduced. But I got another error...
Sorry for bugging you again but do you have any other idea to fix this?

** FYI, I recompiled the project after removal of empty lines by `make clean` and `make`.

#### Error message
```bash
: invalid signal specificationrap: 2
./testing/fdom-fast: line 29: syntax error near unexpected token `$'{\r''
'/testing/fdom-fast: line 29: `wrtab () {
```

#### Current code of fdom-fast
```bash: fdom-fast
#Call ./testing/fdom-fast from one directory up to test the fundamental domain methods. fdom-fast_in is the tests, fdom-fast_out is the expected results
#If your pari.cfg file is NOT in the standard location (/usr/local/lib/pari/pari.cfg), you need to call "make setup" first.
#Exit if we interrupt.
trap exit 2
#Filename to test and the folder to save testing to. Do not add _ to the testing method name.
testname=fdom-fast
testdir=./testing
#The input and output file suffixes.
insuf=_in
outsuf=_out
#Nothing after here should be modified, unless you know what you are doing.
file_in=$testdir/$testname$insuf
file_out=$testdir/$testname$outsuf
file_test=$testdir/$testname-actual.out
file_diff=$testdir/$testname.diff
#Finding locations of the required files and commands.
PARI_CFG_LOC=./paricfg_loc.txt
if test -e $PARI_CFG_LOC; then
  PARI_CFG=$(<$PARI_CFG_LOC)
else
  PARI_CFG=/usr/local/lib/pari/pari.cfg
fi
GPLOC=`grep bindir= $PARI_CFG -s | cut -d"'" -f2`
gp=$GPLOC/gp
VER=`grep pari_release= $PARI_CFG -s | cut -d"'" -f2 | tr . - | cut -d"-" -f1,2,3`
#For printing things.
wrln () { echo "$1"; echo "$1" >&3; }
wr () { echo -n "$1"; echo -n "$1" >&3; }
wrtab () {
  printf %$1s "$2"
  printf %$1s "$2" >&3
}
#Redirect output to save it
exec 3>> $testdir/Bench-$VER
#Make sure files exist
if test ! -r $file_out; then touch $file_out; fi
if test ! -r $file_in; then
  wrln "Error! Missing file, can't test $testname"
  exit 1
fi
#Run it! "pat" tracks the differences and "time" tracks the time taken.
wrtab -27 "* Testing $testname "
(echo 'gettime();0;'; cat $file_in; \
 echo 'print("Total time spent: ",gettime);') \
 | $gp -q --test  > $file_test 2>&1
diff -c $file_out $file_test > $file_diff
pat=`grep "^[-+!] " $file_diff | grep -v "Total time"`
time=`tail -1 $file_test | sed -n 's,.*Total time spent: \(.*\),\1,p'`
rm -f $file_test
wrln
wrln "+++$B Total bench time is $time ms"
#No bugs?
if test -z "$pat"; then wrln "All tests passed!"; exit 0; fi
#Inform the user of bugs found
wrln
wrln "PROBLEMS WERE NOTED. The following file lists them in diff format: $file_diff"
exit 1
```

**Comment by JamesRickards-Canada** [comment]
Thanks!
Interesting, I’m not sure why but your system cares about these carriage returns quite a bit; my setup is very similar. I will try to figure out how to remove them (my guess is that since I saved the file on windows, sometimes that introduces funny characters in the encoding that we don’t see but the program does)
In the meantime, I think you can replace this function with :

wrtab () { printf %$1s "$2"; printf %$1s "$2" >&3; }

(in other words, move it from four lines to one)

In addition, testing is not required to use the actual program! It’s of course good to make sure things seem OK, but I don’t think this issue will affect the actual program itself.

**Comment by JamesRickards-Canada** [comment]
I checked my code, and there are no “\r” characters anywhere
Did you happen to open the file in some sort of editor first? My guess is that the editor (Windows based?) introduced these symbols. If you use something like notepad++, you can view these extra characters, and remove them.

**Comment by Rowing0914** [comment]
> Thanks! Interesting, I’m not sure why but your system cares about these carriage returns quite a bit; my setup is very similar. I will try to figure out how to remove them (my guess is that since I saved the file on windows, sometimes that introduces funny characters in the encoding that we don’t see but the program does) In the meantime, I think you can replace this function with :
> 
> wrtab () { printf %$1s "$2"; printf %$1s "$2" >&3; }
> 
> (in other words, move it from four lines to one)
> 
> In addition, testing is not required to use the actual program! It’s of course good to make sure things seem OK, but I don’t think this issue will affect the actual program itself.

Thank you for your suggestion! I just replaced four lines w/h your suggested line and got more similar errors and changed all multiple lines to single line implementation. After all, I am still getting `syntax error: unexpected end of file`....

> I checked my code, and there are no “\r” characters anywhere
> Did you happen to open the file in some sort of editor first? My guess is that the editor (Windows based?) introduced these symbols. If you use something like notepad++, you can view these extra characters, and remove them.

oh... shoot.. Yes, I opened `fdom-fast` by Sublime Editor with C language interpretation... do you think this is causing this weird issue? I will reclone this repo and recompile!

**Comment by Rowing0914** [comment]
Ohhh! Fixed! `./testing/fdom-fast` finally ran without any error!

```* Testing fdom-fast
+++ Total bench time is 1800 ms
All tests passed!
```

Thank you so much for your prompt assistance!

**Comment by JamesRickards-Canada** [comment]
Oh, awesome!
One more question: did you git clone it from Windows or WSL?
If you did it from windows, then I think GitHub may automatically introduce those characters. I think that this is something I can fix, I.e. tell GitHub to not do this and keep the Unix characters only

**Comment by Rowing0914** [comment]
oh,, that makes sense. I had git-cloned this repo from Windows when I had the issues that we discussed. But this time I git-cloned this repo directly from WSL and now it worked.
